### ISSUE TITLE
Not compatible with Facebook contaner.

### ISSUE THREAD

**Issue by mvrhov** [Drive4ik/simple-tab-groups#572]
**Describe the bug**
When the tabs are in a container e.g personal... An you try to open a link from something like gmail.. that links to the facebook you are greeted with "Can't open the URL into XXX container"

Another addon, which has UUID:
45a70e8a-9f74-4d19-90ac-22e1886f4644

tries to open this URL in Facebook container. Move the tab to another group or forbid the addon 45a70e8a-9f74-4d19-90ac-22e1886f4644 to perform this action.

You can find out the addon by UUID on the page:...

**Expected behavior**
There should be a setting to allow the fb container to take precedence.

**Comment by Drive4ik** [comment]
Done. You can exclude needed containers in group settings or on `Can't open the URL into XXX container` page. Update will available on next release.

**Comment by Ludomancer** [comment]
I think I might be still seeing similar behavior.

Setup:
My Default group is set to change the container to Personal.
It is set to ignore Facebook Container all other containers except for the "no container" option.

![image](https://user-images.githubusercontent.com/6220948/87336847-6b77a680-c53a-11ea-96d3-5b53903487b1.png)


Result:
When I open "facebook.com", I believe Facebook Container and STG is conflicting and after bit of tabs openning closing erratically I end up having 2 tabs with "www.facebook.com" URL opened in Facebook Container.

![image](https://user-images.githubusercontent.com/6220948/87336903-7d594980-c53a-11ea-97ec-b23f17d3d586.png)

**Comment by Ludomancer** [comment]
@Drive4ik 

I can create a new issue for this if that works better for you. I can see this behavior happening as described above.

**Comment by Drive4ik** [comment]
Tried to fix this bug again, wait for next addon update.
