### ISSUE TITLE
Tabs missing from Group after closing / restarting Firefox

### ISSUE THREAD

**Issue by Tyrewt** [Drive4ik/simple-tab-groups#62]
Version 2.3.1 isn't restoring Tabs once Firefox is closed and then reopened. Upon reopening, Tabs appear to be intact for whichever group you left off on, however, the total number only states 1 when clicking the Simple Tab Group icon to view the Group list.

Additionally, whichever group is selected when you close Firefox and then reopen it, ALL Tabs will be lost, You will see that the total number of Tabs are reset down to 1 and completely gone for that group.

Firefox 58.

**Comment by Drive4ik** [comment]
You need to enable this in your browser settings
![screenshot_2](https://user-images.githubusercontent.com/7843031/35385637-a19e86ea-01d1-11e8-81d3-ea0f873bf5f6.png)

**Comment by me21** [comment]
It doesn't help. Tabs are restored but they do not belong to a group anymore.

**Comment by me21** [comment]
Wait, it seems it works for me with version 2.3.1. Maybe it's version 2.3 that was buggy. I'll check one more time. Now, closing the Firefox...

**Comment by me21** [comment]
...and reopening it. All tabs are currently in place.

**Comment by Drive4ik** [comment]
I'm glad that the problem was solved

**Comment by Tyrewt** [comment]
This is NOT fixed. There are three outstanding issues.

"Show your windows and tabs from last time" is enabled. 

Issue 1: Upon launching Firefox, note how in the current window (Group 1) there are 4 Tabs, yet the Tab Group menu on the top right counter only indicates "1".

![screenshot from 2018-01-25 19-31-18](https://user-images.githubusercontent.com/21961083/35419741-b90f9e50-0207-11e8-8e4e-7c1ba4c52af0.png)

Issue 2: While Firefox is still open, I then switch to Group 2 which also has 4 Tabs, but the counter is correctly indicating 4 Tabs. I then close Firefox and launch again. Naturally once Firefox opens I am where I left off on Group 2. But, now the same issue outlined above affects Group 2. As you can see, the window has 4 Tabs present but the count on Group 2 is incorrectly indicating only 1. 

![screenshot from 2018-01-25 19-31-46](https://user-images.githubusercontent.com/21961083/35419747-bf92f358-0207-11e8-85f9-9c7d359150ba.png)

Issue 3: With the browser still open, I switch from Group 2 back over to Group 1, now the window only has 1 Tab and the count is reported correctly as 1. However, the other Tabs have been DELETED from the past session. This occurs on any Group you have selected when the browser is closed.

![screenshot from 2018-01-25 19-31-56](https://user-images.githubusercontent.com/21961083/35419753-c4ea4284-0207-11e8-8c97-bc7937407c3b.png)


I should also mention that Group 2 and Group 3 were imported using "Restore Quicksaver's Tab Groups" option, perhaps that has something to do with it?

**Comment by me21** [comment]
On the next day I have to confirm this is not fixed. After opening Firefox, I now have 1 tab in the current group, even though all tabs are open, but they don't belong to tab group anymore.

As a workaround, it is possible to backup tab groups before closing Firefox and restore as needed. But it is inconvenient, of course.

**Comment by me21** [comment]
@Tyrewt @Drive4ik I've noticed that if I click on the inactive tab, it is reloaded and added to the tab group. Maybe that's helpful somehow.

**Comment by Drive4ik** [comment]
Hi all! can you please backup you tab groups, uninstall it and install this TEST build?
Notice:
rename this file from
*test_simple_tab_groups-2.3.1-an+fx.xpi.zip*
to
*test_simple_tab_groups-2.3.1-an+fx.xpi*


[test_simple_tab_groups-2.3.1-an+fx.xpi.zip](https://github.com/Drive4ik/simple-tab-groups/files/1667981/test_simple_tab_groups-2.3.1-an.fx.xpi.zip)


and re-test this issue?

**Comment by Drive4ik** [comment]
@Tyrewt please, can you retest too with this test addon build from prev message?

**Comment by meru448** [comment]
Tyrewt description much more accurately describes what I experienced, I don't know how to make the issue happen again, but I will uninstall & download the modified version.

**Comment by Drive4ik** [comment]
don't forget backup you data before uninstall!

**Comment by meru448** [comment]
Done, will proceed to use normally & post if the issue occurs again. // will this test version update automatically to 2.3.2 etc or should I keep an eye out for updates? 

Many thanks btw, this addon, er extension as it were these days has been amazing.

**Comment by Tyrewt** [comment]
@Drive4ik Yes, I will evaluate the patch this evening.  I'll report back with my findings as I now know how to replicate the issue(s), please keep open until then.

**Comment by Drive4ik** [comment]
No, this is test unstable version and you need to delete it.
If other users don't find any bugs I will update global version

**Comment by Drive4ik** [comment]
@Tyrewt , I can't close this issue until the problem is resolved.

Thanks for helping!

**Comment by Tyrewt** [comment]
@Drive4ik Testing completed.

1. A suggestion for improvement. Prior to uninstall I used the "Backup your Simple Tab Groups" option to create a backup. You should add a comment that indicates where the backup file is saved, currently it saves to the Downloads folder with no option to select a path and I was expecting it to be in with my Firefox profile.

2. I have confirmed this TEST build corrects the issue(s) outlined in my bug report. All Tabs are intact and the Group counts are now accurate. 

3. While testing I've discovered a new issue #66

**Comment by me21** [comment]
@Tyrewt 1. Depends on Firefox download settings. You can set it so that Firefox prompts for download location every time you save something.

**Comment by Drive4ik** [comment]
@Tyrewt thanks for testing)
@me21 thanks for testing too)

@Tyrewt go to browser settings and check this
![screenshot_1](https://user-images.githubusercontent.com/7843031/35472334-0582c478-0376-11e8-98f2-4025b0a12fef.png)

**Comment by me21** [comment]
I didn't test, I wrote about version 2.3.1.

----- Ответное сообщение -----
От: "Drive4ik" <notifications@github.com>
Кому: "Drive4ik/simple-tab-groups" <simple-tab-groups@noreply.github.com>
Копия: "Alexandr Zarubkin" <me21@yandex.ru>, "Mention" <mention@noreply.github.com>
Тема: [Drive4ik/simple-tab-groups] Tabs missing from Group after closing / restarting Firefox (#62)
Дата: сб, янв. 27, 2018 16:24

@Tyrewt thanks for testing)
@me21 thanks for testing too)

@Tyrewt go to browser settings and check this
![screenshot_1](https://user-images.githubusercontent.com/7843031/35472334-0582c478-0376-11e8-98f2-4025b0a12fef.png)

**Comment by me21** [comment]
I didn't test, I wrote about version 2.3.1.

**Comment by Tyrewt** [comment]
@Drive4ik Oh okay, thanks.  I believe this issue is fixed with the TEST build.

**Comment by Drive4ik** [comment]
Please, re-test this issue in latest version v2.3.5

**Comment by me21** [comment]
Updated to v2.3.6, no issues so far.

**Comment by Drive4ik** [comment]
Please, open this issue if it's replicated
Thanks

**Comment by Tyrewt** [comment]
@Drive4ik Confirmed fixed - Tested 2.3.6.  FYI, your work has on this Add-on has allowed me to finally upgrade to the latest Firefox, Simple Tab Groups is a direct replacement and ever BETTER than QucikSilver's Tab Group! Thank you for your contribution.

**Comment by me21** [comment]
@Drive4ik Yeah, I fully agree with **Tyrewt**. Большое спасибо :-)

**Comment by Drive4ik** [comment]
@me21 
Пожалуйста :)

Кстати, это оказался не просто баг а довольно серьезный:
https://bugzilla.mozilla.org/show_bug.cgi?id=1435077

там есть gif анимация
----------------------------------------------------
By the way, it was not just a bug but rather serious
there is gif animation
